[build]
  # No site build needed; we only deploy Netlify Functions.
  command = "echo skip build"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "ccxt",
    "http-proxy-agent",
    "https-proxy-agent",
    "socks-proxy-agent",
    "protobufjs",
    "node-fetch"
  ]

# Clean webhook path so your function isn't exposed
[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/telegram"
  status = 200
